apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }} #from RELEASE NAME
spec:
  selector:
    matchLabels:
      app: music
  replicas: {{ .Values.replicase }}  #from values
  template:
    metadata:
      labels:
        app: music
    spec:
      containers:
      - name: {{ .Values.containers.name }} #from values
        image: {{ .Values.containers.image }} #from values
        ports:
        - containerPort: 8080