kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }} #from RELEASE NAME
spec:
  selector:
    app: music
  type: {{ default "NodePort" .Values.type }}  #from values | DEFAULT TO NODEPORT
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080