apiVersion: apps/v1
kind: Deployment
metadata:
  name: animals-deployment-moose
  labels:
    app: animals-moose
spec:
  replicas: 2
  selector:
    matchLabels:
      app: animals-moose
  template:
    metadata:
      labels:
        app: animals-moose
    spec:
      containers:
      - name: animals
        image: supergiantkir/animals:moose
        ports:
        - containerPort: 80