apiVersion: v1
kind: Service
metadata:
  name: animals-service-bear
spec:
  selector:
    app: animals-bear
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: 80