apiVersion: v1
kind: Service
metadata:
  name: spring-music-service
spec:
  selector:
    app: spring-music
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer