apiVersion: v1
kind: Pod
metadata:
  name: taltr
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /storage
      name: app-storage
  - name: animals
    image: yanivomc/spring-music:latest
    ports:
    - containerPort: 8080
    volumeMounts:
    - mountPath: /storage
      name: app-storage
  volumes:
  - name: app-storage
    hostPath:
      # directory location on host
      path: /tmp/files
      # this field is optional
      type: DirectoryOrCreate