apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: apps
spec:
 replicas: 2
 selector:
  matchLabels:
    app: app
 template:
  metadata:
   labels:
    app: app
  spec:
    nodeSelector:
      env: FRONTENED
    containers:
    - name: app1
      image: supergiantkir/animals:bear
      ports:
      - containerPort: 80
      volumeMounts:
      - mountPath: /storage/app1
        name: app-storage
    - name: app2
      image: yanivomc/spring-music:latest
      ports:
      - containerPort: 3000
      volumeMounts:
      - mountPath: /storage/app2
        name: app-storage
    volumes:
      - name: app-storage
        hostPath:
          path: /tmp/files