apiVersion: v1
kind: Pod
metadata:
  name: taltr
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
  - name: animals
    image: yanivomc/spring-music:latest
    ports:
    - containerPort: 8080